# Generated by Django 5.1.6 on 2025-02-23 10:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmergencyInfo",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("blood_group", models.CharField(max_length=5)),
                ("address", models.TextField()),
                ("emergency_contact", models.CharField(max_length=15)),
                ("medical_conditions", models.TextField(blank=True, null=True)),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
            ],
        ),
    ]
