# Generated by Django 5.1.6 on 2025-02-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergency_info", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencyinfo",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
